version: '3.7'

services: 
  gunicorn: 
    image: gunicorn:latest
    container_name: gunicorn
    volumes: 
      - ./django/:/usr/src/app/
      - gunicorn:/var/run/gunicorn

  nginx: 
    image: nginx:1.21.6
    container_name: nginx
    ports: 
     - 80:80
    depends_on: 
      - gunicorn
    volumes: 
     - ./nginx/gunicorn.conf:/etc/nginx/conf.d/default.conf
     - gunicorn:/var/run/gunicorn
  
volumes: 
  gunicorn: 
    driver: local