version: '3.7'

services: 
  app: 
    build: ./django
    container_name: app
    volumes: 
      - gunicorn:/var/run/gunicorn
      - static:/usr/share/nginx/html/static
    environment:
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - HOST=${HOST}

  web: 
    build: ./nginx
    container_name: web
    ports: 
     - 80:80
    depends_on: 
      - app
    volumes: 
     - gunicorn:/var/run/gunicorn
     - static:/usr/share/nginx/html/static


      
  
volumes: 
  gunicorn: 
    driver: local
  db-store:
  static: