version: '3.7'

services: 
  app: 
    build: ./django
    container_name: app
    volumes: 
      - gunicorn:/var/run/gunicorn
      - static:/usr/share/nginx/html/static

  web: 
    build: ./nginx
    container_name: web
    ports: 
     - 80:80
    depends_on: 
      - gunicorn
    volumes: 
     - gunicorn:/var/run/gunicorn
     - static:/usr/share/nginx/html/static

  db:
    build: ./mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db-store:/var/lib/mysql
  
volumes: 
  gunicorn: 
    driver: local
  db-store:
  static: